modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/lilgallon/AimAssistanceMod/issues"
license="MIT License"

[[mods]]
modId="aimassistancemod"
version="1.4.0"
displayName="Aim Assistance"
updateJSONURL="https://raw.githubusercontent.com/lilgallon/AimAssistanceMod/MC_1.16.3/update.json"
displayURL="https://github.com/lilgallon/AimAssistanceMod/"
# logoFile="examplemod.png"
# credits="someone"
authors="@lilgallon on github"
description='''
A minecraft mod that helps aiming (at mods, blocks, but not players). Made for players using controllers or even disabled players with difficulties to aim.'''