name: build fabric
on:
  pull_request:
    branches: [ "**" ]
    paths:
      - .github/workflows/build-fabric.yaml
      - build.gradle.kts
      - gradle.properties
      - gradle/**
      - common/**
      - fabric/**
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/build-fabric.yaml
      - build.gradle.kts
      - gradle.properties
      - gradle/**
      - common/**
      - fabric/**

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Gradle Build
        run: ./gradlew :fabric:build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: fabric/build/libs/
